services:
  web:
    image: nginx
    ports:
     - 80:80

  app:
    image: python:3.14
    working_dir: /app
    ports:
    - 8000:8000
    volumes:
      - .:/app
    command: bash -c "pip install -r requirements.txt && python3 app.py"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: appdb

